CREATE TABLE CART (
    PRODUCT_ID VARCHAR(20),
    CUSTOMER_ID VARCHAR(20),
    AMOUNT INT,
    LAST_UPDATE DATE
    CONSTRAINT FK_CART_PRODUCT FOREIGN KEY PRODUCT_ID REFERENCES PRODUCT(PRODUCT_ID)
)

CREATE TABLE CUSTOMER (
    CUSTOMER_ID VARCHAR(20) PRIMARY KEY,
    DATE_REGISTER DATE,
    ADDRESS VARCHAR(100),
    PHONE_NUMBER CHAR(10),
    EMAIL VARCHAR(50),
    NAME VARCHAR(50),
    ADMIN INT,
    PASSWORD VARCHAR(50)
)


GRANT SELECT, INSERT, UPDATE, DELETE ON PRODUCT TO CUSTOMER WHERE ADMIN = 1;
GRANT SELECT, INSERT ON CART TO CUSTOMER WHERE ADMIN = 0;
