CREATE TABLE CART (
    CART_ID VARCHAR(20) PRIMARY KEY,
    PRODUCT_ID VARCHAR(20),
    CUSTOMER_ID VARCHAR(20),
    AMOUNT INT,
    LAST_UPDATE DATE
)

CREATE TABLE CUSTOMER (
    CUSTOMER_ID VARCHAR(20) PRIMARY KEY,
    DATE_REGISTER DATE,
    ADDRESS VARCHAR(100),
    PHONE_NUMBER CHAR(10),
    EMAIL VARCHAR(50),
    NAME VARCHAR(50),
    ADMIN BOOLEAN,
    PASSWORD VARCHAR(50)
)

