CREATE TABLE ORDERS (
	ORDER_ID VARCHAR(20) PRIMARY KEY,
	CUSTOMER_ID VARCHAR(20),
	ORDER_DATE DATE,
	TOTAL VARCHAR(20),
	ORDER_STATUS VARCHAR(50)
	CONSTRAINT FK_ORDER_CUSTOMER FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMER(CUSTOMER_ID)
)

CREATE TABLE ORDER_ITEMS (
    ITEM_ID INT IDENTITY(1,1) PRIMARY KEY,
    ORDER_ID VARCHAR(50),
    PRODUCT_ID VARCHAR(50),
    AMOUNT INT,
    CONSTRAINT FK_OrderItems_Order FOREIGN KEY (ORDER_ID) REFERENCES ORDERS(ORDER_ID),
    CONSTRAINT FK_OrderItems_Product FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCT(PRODUCT_ID)
);

CREATE TABLE INVOIVE (
	INVOICE_ID VARCHAR(20) PRIMARY KEY,
	ORDER_ID VARCHAR (20),
	PAYMENT_METHOD VARCHAR(50),
	PAYMENT_CODE VARCHAR(50),
	PAYMENT_STATUS VARCHAR(50),
	CONSTRAINT FK_INVOICE_ORDER FOREIGN KEY (ORDER_ID) REFERENCES ORDERS(ORDER_ID)
)