CREATE TABLE VOUCHER
(
    VOUCHER_ID VARCHAR(15) PRIMARY KEY,
    MONEY_OFF VARCHAR(15),
    PERCENTAGE_OFF DECIMAL(4, 2),
    EXPIRY DATE,
    CONSTRAINT CHK_VALUE_RANGE CHECK (column_name > 0 AND column_name < 1),
    CONSTRAINT CHK_DISCOUNT_TYPE CHECK 
    (
        (MONEY_OFF IS NULL AND PERCENTAGE_OFF IS NOT NULL) OR 
        (MONEY_OFF IS NOT NULL AND PERCENTAGE_OFF IS NULL)
    ),
);